STOCKS_BR = [
    # Ações BR
    'ITUB4', 'BBAS3', 'BPAC11', 'ROXO34', 'BBSE3', 'CXSE3', 'ITSA4', 'SOJA3', 
    'MDIA3', 'LREN3', 'AZZA3', 'VIVA3', 'GRND3', 'VULC3', 'EZTC3', 'JHSF3', 
    'LAVV3', 'RENT3', 'COGN3', 'RADL3', 'ODPV3', 'WEGE3', 'MILS3', 'GOAU4', 
    'KLBN11', 'VIVT3', 'EGIE3', 'EQTL3', 'ISAE4', 'AURE3', 'SBSP3', 'SAPR11', 
    'BMOB3', 'GMAT3',
    
    # FIIs BR
    'HGLG11', 'BTLG11', 'XPML11', 'ALZR11', 'VISC11', 'LVBI11', 'KNCR11', 
    'KNRI11', 'TRXF11', 'HFOF11', 'HGBS11', 'PVBI11', 'BRCR11', 'GARE11', 
    'MXRF11', 'GGRC11', 'BRCO11', 'MCCI11', 'HSML11', 'RBRR11', 'KNHF11'
]
TICKERS_BR = [f"{t}.SA" for t in STOCKS_BR]

TICKERS_US = [
    # Ações EUA
    'RACE', 
    
    # ETF Bonds
    'TFLO', 'USFR', 
    
    # REITs
    'ADC', 'O', 'VICI', 'NNN', 'DLR'
]

TICKERS_CRYPTO = ['BTC-USD']

ALL_TICKERS_YAHOO = TICKERS_BR + TICKERS_US + TICKERS_CRYPTO